/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stevan_popov_Crypto */

#ifndef _Included_stevan_popov_Crypto
#define _Included_stevan_popov_Crypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stevan_popov_Crypto
 * Method:    crypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_stevan_popov_Crypto_crypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
